name = "bulkflow-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "campaign-db"
database_id = "2b26f100-3822-48d6-8c8b-4b984902004e"

[triggers]
crons = ["*/2 * * * *"]
